=== urospetrovic34/Provera_znanja/magacin.dtd
<!ELEMENT Magacin (Artikal*)>
<!ELEMENT Artikal (Naziv,DatumIzrade,Cena,Kompanija,Email+)>
<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv sifraArtikla CDATA #REQUIRED>
<!ELEMENT DatumIzrade (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena tipCene (dinar|evro) "dinar">
<!ELEMENT Kompanija (Ime,Adresa+)>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT Adresa (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email dostupnost (privatni|sluzbeni) "privatni">

=== urospetrovic34/Provera_znanja/magacin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">
<Magacin>
<Artikal>
	<Naziv sifraArtikla=""></Naziv>
	<DatumIzrade>
		<Dan></Dan>
		<Mesec></Mesec>
		<Godina></Godina>
	</DatumIzrade>
	<Cena tipCene="dinar"></Cena>
	<Kompanija>
		<Ime></Ime>
		<Adresa></Adresa>
	</Kompanija>
	<Email dostupnost="privatni"></Email>
</Artikal>
</Magacin>
